# mkdocs.yml
site_name: News Trading System

theme:
  name: "material"
  custom_dir: "docs/n2_custom_theme"
  logo: "img/logo-96px.png"
  palette:
    primary: 'blue'
    accent: 'blue'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra_css: 
- css/dark_theme.css
- css/codehilite.css
- css/profont.css
- css/youtube-videos.css
- css/nta-weekly-schedule-cards.css
- https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.js
  - js/lot-size-calc.js
  - js/filter-events.js


plugins:
- search
- mkdocstrings

nav:
  - Intro: index.md
  - Weekly Schedules:
    - 2023:
      - Week 14: weekly-schedules/2023/week-14-schedule.md
      - Week 15 (+€592.40 DEMO): weekly-schedules/2023/week-15-schedule.md
      - Week 16 (0 pips | +0% | +€0.00): weekly-schedules/2023/week-16-schedule.md
      - Week 17: weekly-schedules/2023/week-17-schedule.md
      - Week 18: weekly-schedules/2023/week-18-schedule.md
      - Week 19: weekly-schedules/2023/week-19-schedule.md
    - 2024:
      - Week 5 (current): weekly-schedules/2024/week-05-schedule.md
      - Week 6: weekly-schedules/2024/week-06-schedule.md
      - Week 7: weekly-schedules/2024/week-07-schedule.md
      - Week 8: weekly-schedules/2024/week-08-schedule.md
  - Blog:
    - (EN) News Trading System Explained: system-explained-en.md
    - (DE) News Trading System erklärt: system-explained-de.md

edit_uri: '#docs/'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  # - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - attr_list
  - md_in_html
  # - fontawesome_markdown
